export const Recipes = [
    {
        id: 100,
        name: "Butter Chicken",
        image: "https://media.istockphoto.com/id/639390540/photo/indian-butter-chicken.jpg?s=2048x2048&w=is&k=20&c=U_t-jEbSS9NOuCXjcm3zLT4JS631JVyMUHDumPZ1DbI=",
        category: "Chicken",
        ingredients: "Boneless Chicken 500 gms, Kahmiri Red Chilli Powder 1 tsp, Lemon Juice 1 tbsp, Salt or to taste 1 tsp, Butter 2 tbsp, Yoghurt 1/2 cups, Ginger Paste 3 tsp, Garlic Paste 3 tsp, Red Chili Powder 1/2 tsp, Garam Masala Powder 1/2 tsp, Mustard Oil 1 tsp, Tomtato Puree 2 cups, Butter 4 tbsp, Mace 1 nos, Green Cardamom 4 nos, Red Chilli Powder 1 tsp, Dry Fenugreek Leaves 1/2 tsp, Honey 1 tbsp ,  Fresh Cream 2 tbsp",
        description: "Wash the chicken pieces properly. Drain the water and pat dry. Marinate with kashmiri red chilli powder, salt and lemon juice. Refrigerate for 30 minutes.In a bowl whisk together yogurt, half of ginger paste, half of garlic paste, red chilli powder, garam masala powder, salt and mustard oil. Marinate the chicken pieces in the mixture and again refrigerate for 2 hours.After 2 hours, bring the chicken pieces to the room temperature. Grill them till done.Add the marinated mixture too while grilling. In a non-stick pan, heat 2 tbsp butter, add green cardamom, mace, ginger paste, garlic paste and saute till the raw smell goes away. Now add the tomato puree, salt, red chilli powder and cook for 15-20 mins.Meanwhile, check the chicken. Once done cut them into small pieces.After 15 minutes, add crushed fenugreek leaves, honey, fresh cream to the gravy and cook for another 2-3 minutes.Finally add the chicken pieces and cook till the gravy is consistent.Serve your Butter Chicken with roti, Naan or kulcha."
    },
    {
        id: 101,
        name: "Mutton Korma",
        image: "https://thumbs.dreamstime.com/z/mutton-curry-28836468.jpg?w=768",
        category: "Mutton",
        ingredients: "Lamb/Goat/ Mutton Meat 1 kgs, Fresh unsweetened Yogurt 1 cups, Cooking oil 3-4 tbsp, Onions, finely chopped 3 nos, Eastern Ginger-Garlic Paste 4 tsp, Cinnamon 2 nos, Clove 6 nos, Peppercorns 10 nos, Mace 2 nos, Green Cardamom pods split into two 5 nos, Eastern Coriander Powder 2 tsp, Eastern Cumin Powder 1 tsp, Eastern Turmeric Powder 1 tsp, Eastern Chili Powder 1/2 tsp, Eastern Nutmeg Powder 1/4 tsp, tomatoes, finely chopped 2 nos, Coriander leaves, fresh to garnish 2 tbsp, Salt to taste 1 pinch",
        description: "Preparation-Thoroughly wash the lamb, drain and put into a large mixing bowl, Add the yogurt and mix to coat the meat well, Set aside, Cooking--Heat the cooking oil in a deep, heavy bottomed pan on medium flame, When hot, add the onions and fry till almost pale golden, Add the ginger and garlic pastes and fry for 1 minute, Stir often to prevent burning, Add all the whole spices and fry for 1 minute – or till spices are slightly darker in color, Now add all the powdered spices and fry till the oil begins to separate from the masala (spice mix), Stir often to prevent burning, If required, sprinkle a little water from time to time to prevent the masala from burning, Add the marinated meat to this and fry till the meat is sealed, Add the tomatoes, salt to taste and fry till the tomatoes are pulpy, Stir often to prevent spices burning, Do not cook on high heat, Once tomatoes are pulpy, simmer the heat, cover the pan and cook till meat is done, This dish should have a thick gravy so ideally, water is not added while cooking, If however, you find it getting too dry, 1/2 a cup of warm water can be added to it, When the meat is cooked and tender, remove pan from heat and transfer Korma into a serving dish, Garnish with freshly chopped coriander, Tastes with breads like Chapatis, Parathas or Naans, and boiled rice,"
    }, 
    {
        id: 102,
        name: "Kadhai Paneer",
        image: "https://media.istockphoto.com/id/968505648/photo/indian-food-or-indian-curry-in-a-copper-brass-serving-bowl-with-bread-or-roti.jpg?s=2048x2048&w=is&k=20&c=Qcy_znnfnM9zMsiskBEma3RZ6xr6YukE5vxizrg-Avc=",
        category: "Veg",
        ingredients: "paneer (cottage cheese) 1 1/2 cups, Oil for deep-frying 2 cups, oil 1 tbsp, finely chopped onions 1/2 cups, recipe basic kadhai gravy 1 cups, coriander-cumin seeds (dhania-jeera) powder 1 tsp, Eastern turmeric powder (haldi) 1/4 tsp, Eastern chilli powder 1 tsp, Eastern garam masala 1/2 tsp, dried fenugreek leaves (kasuri methi) 1/4 tsp, sliced capsicum 1/2 cups, sugar 1 pinch, fresh cream 1/2 cups, Fresh coriander leaves to Garnish 1 sprig, Salt to taste 1 pinch",
        description: "Heat the oil in a kadhai and deep-fry the paneer pieces till they turn light brown in colour, Drain on absorbent paper and place in lukewarm water for 10 minutes, Heat the oil in a kadhai, add the onions and sauté on a medium flame till they turn translucent for approx 3 to 4 minutes, Add the kadhai gravy, coriander-cumin seeds powder, chilli powder, turmeric powder, garam masala, dried fenugreek leaves and sauté on a medium flame for another minute, Add the capsicum, 1 cup water, mix well and cook on a medium flame for 2 to 3 minutes, while stirring once in between, Add the paneer, salt and cook on a slow flame for another 2 to 3 minutes, Add the cream, mix well and serve hot garnished with coriander, Best served with Indian breads like Naan and Chappati"
    },
    {
        id: 103,
        name: "Tandoori Roast Chicken with Potatoes",
        image: "https://myfoodbook.com.au/sites/default/files/styles/card_c_molo/public/recipe_photo/butterflied_tandoori_chicken_passage_to_india.jpeg",
        category: "Chicken",
        ingredients: "1 x 1-1.2kg butterflied chicken,1 x 150g Passage to India Tandoori Paste,	1 cup (125ml) plain Greek yoghurt	1 lemon, plus extra wedges to serve	2 red onions, thickly sliced, 2 tablespoons oil	500g chat potatoes, halved Fresh coriander, raita and your favourite Indian breads to serve",
        description: "Wipe chicken with damp paper towel and pat dry. Score breast and thighs with a sharp knife	Combine Tandoori Paste, yoghurt and juice of half a lemon. Spoon over both sides of the chicken. Cover and refrigerate for 20 minutes or as long as time permits, Preheat oven 220C/200C (fan-forced)	Place sliced red onion into base of a baking dish and place chicken on top, skin side up. Drizzle with oil and roast for 30 minutes	Meanwhile, boil, steam or microwave chat potatoes until just tender. Drain and set aside Remove chicken from oven and add potatoes to tray. Cook a further 15-20 minutes or chicken is cooked through. Loosely cover chicken in foil and rest for 10 minutes	Just before serving, squeeze over fresh lemon juice. Garnish with fresh coriander and serve with extra lemon wedges. Serve with roasted potatoes and onions, raita and Indian breads. Tips & Hints:	Butterflied chicken can be purchased from supermarkets. Alternatively, ask your butcher to butterfly it for you	Check chicken is cooked by piercing thigh with a knife. If the juices run clear, the chicken is cooked	Cook Indian recipes at home with Tandoori Curry Paste"
    },
    {
        id: 104,
        name: "Quick Sweet Chilli Chicken Stir-fry",
        image: "https://myfoodbook.com.au/sites/default/files/styles/card_c_molo/public/recipe_photo/Quick_Sweet_Chilli_Stirfry_web_crop.jpeg",
        category: "Chicken",
        ingredients: "⅔ cup (160ml) Rosella Organic Sweet Chilli Sauce	¼ cup (60ml) light soy sauce, ¼ cup (60ml) Chinese rice wine, 3 cloves garlic, chopped 2 teaspoons cornflour, 400g organic chicken breast fillets, thinly sliced, 2 tablespoons vegetable oil, 1 onion, cut into thin wedges, 1 red capsicum, cut into 1cm thick slices	250g baby corn, cut lengthways 4 green onions, cut into 3cm lengths, Steamed rice and coriander to serve",
        description: "Combine sweet chilli, soy sauce, rice wine, garlic and cornflour and mix well. Stir ¼ cup through the chicken. Mix well Heat half the oil in a wok or frying pan over high heat. Stir fry chicken in batches for 4-5 minutes or until golden. Remove and transfer to a plate	Add remaining oil and onion, red capsicum, baby corn and green onion. Stir fry for 3-4 minutes. Return chicken and remaining sauce to wok. Stir fry until chicken is cooked through and sauce has thickened. Serve immediately over steamed rice. Garnish with fresh sprigs of coriander.Tips & Hints:	Chicken can be marinated overnight. Cover and refrigerate.	Chinese rice wine is available in the Asian grocery aisle of your supermarket	Use this sauce as a great marinade. Toss through chicken wings or drumsticks. Pack into freezer bags. Label and date and freeze for 3-6 months. Defrost in the refrigerator overnight and roast in a hot oven	Swap out chicken breast for firm cubes of tofu or beef stir-fry strips. Use your preferred stir-fry or seasonal vegetables, such as broccoli, carrot and mushrooms"
    }
]
																																																																																							